name: cPanel Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 🚚
        uses: actions/checkout@v3

      - name: Install Dependencies 📦
        run: npm install

      - name: Set environment variables
        run: |
          echo "REACT_APP_SUPABASE_CLIENT_URL=${{ secrets.REACT_APP_SUPABASE_CLIENT_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_SUPABASE_PROJECT_KEY=${{ secrets.REACT_APP_SUPABASE_PROJECT_KEY }}" >> $GITHUB_ENV

      - name: Supabase - React Book 🏗️
        run: npm run build

      - name: Upload to cPanel over SFTP 📂
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GIT_ACTIONS_CPANEL_REACT_BOOKS_FTP_SERVER }}
          username: ${{ secrets.GIT_ACTIONS_CPANEL_REACT_BOOKS_FTP_USERNAME }}
          password: ${{ secrets.GIT_ACTIONS_CPANEL_REACT_BOOKS_FTP_PASSWORD }}
          port: 21098
          source: "build/*"
          target: "/"
          strip_components: 1
          overwrite: true
